### PR TITLE
Make quote/reply box color dark

### PR DESCRIPTION
**Pull request by jodizzle**
Before:
rocketchat_white_quote_box
After:
rocketchat_dark_quote_box
I just went with `sidebar-bg` as the color, but maybe a different shade would be better?

Also, not sure where the extra `-webkit-` stuff is coming from, it just showed up I built `dist/`.  I can exclude those lines if that's preferable.

### CODE REVIEW

**Comment by eryg-kai** [comment]
Sweet! Thanks for the PR. Ideally we would use `component-bg` for this over `sidebar-bg`. If you're feeling up to it, it's probably not a bad idea to remove the border and extra top padding inside the reply as well because that definitely doesn't look great.

No worries about the `-webkit` stuff, the auto-prefixer will do as the auto-prefixer does, and who are we to question its mysterious ways. :stuck_out_tongue:

**Comment by jodizzle** [comment]
Thanks!  I'll look at using `component-bg` and removing the stuff you mentioned.

**Comment by jodizzle** [comment]
@0x0049 I pushed some changes.  Was this what you were thinking?
rocketchat_dark_quote_box_2

**Comment by eryg-kai** [comment]
Fantastic! Thanks for fixing this.

**Pull request merged**
